site_name: "Cookbook Coopératif de l'Amagda"
nav:
  - Accueil: index.md
theme:
  name: material
docs_dir: docs         # dossier source des fichiers Markdown (par défaut 'docs')
site_dir: _build       # dossier de sortie statique (remplace 'site') 
theme:
  name: material       # ou tout autre thème installé
markdown_extensions:
  - toc:
      permalink: true
  - attr_list      # nécessaire pour ajouter des classes HTML
  - md_in_html     # autorise le HTML en-ligne dans Markdown
plugins:
  - search
  - awesome-pages  # pour ordonner automatiquement les dossiers 
