name: Build & Deploy MkDocs

on:
  push:
    branches:
      - master     # ou 'master', selon votre branche par défaut

permissions:
  contents: write   # nécessaire pour pousser sur gh-pages

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          pip install mkdocs mkdocs-material

      - name: Build site to _build/
        run: mkdocs build --site-dir _build   # génère dans ./_build :contentReference[oaicite:2]{index=2}

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_build                # publie ./_build sur gh-pages :contentReference[oaicite:3]{index=3}
